FROM php:8.4-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    unzip \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install -j"$(nproc)" pdo pdo_pgsql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY php-fpm.d/zz-vep.conf /usr/local/etc/php-fpm.d/zz-vep.conf

WORKDIR /var/www

CMD ["php-fpm"]
